default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: RailsClone_development
test:
  <<: *default
  database: RailsClone_test

production:
  <<: *default
  database: RailsClone_production
  username: RailsClone
  password: <%= ENV['RAILSCLONE_DATABASE_PASSWORD'] %>
